(() => {
  "use strict";

  const REQUEST_EVENT = "oweh:game-command";
  const RESULT_EVENT = "oweh:game-command-result";
  const PING_EVENT = "oweh:game-ping";
  const ALLOWED = new Set([
    // pet_name names an Unnamed newborn (its profile has a Name button, not Rename).
    "pets_enclosure", "pet_rename", "pet_name", "pet_feed",
    "friend_request", "friend_remove", "pet_breed", "pet_turn_egg", "pet_sendto"
  ]);

  // Confirmed live 2026-10-05 on an owned pet and an owned egg: Edit > Send To opens a confirm
  // dialog with select[name="SendTo"] (pet: adoption_center | discard, egg: discard) and then
  // calls ui_action_cmdExec('pet_sendto', 'PetID=<id>', form, ...). The bridge lets through
  // only the Discard choice, and only for the surplus list the user confirmed.
  function isConfirmedDiscard(command, purpose, fields) {
    const names = fields && typeof fields === "object" ? Object.keys(fields) : [];
    return command === "pet_sendto" && purpose === "confirmed-discard"
      && names.length === 1 && names[0] === "SendTo" && String(fields.SendTo) === "discard";
  }

  function isOwnHatcheryRoute() {
    const hash = String(window.location?.hash || document.location?.hash || "");
    return /src=pets&sub=hatchery/.test(hash) && !/[?&]usr=\d+/.test(hash);
  }

  function isVisibleOwnHatchTarget(targetId) {
    if (!isOwnHatcheryRoute()) return false;
    for (const icon of document.querySelectorAll?.('img[title="Hatch Egg"]') || []) {
      const card = icon.closest?.("li") || icon.parentElement?.parentElement;
      const href = card?.querySelector?.('a.pet[href*="pet="]')?.getAttribute?.("href") || "";
      if (href.match(/[?&]pet=(\d+)/)?.[1] === String(targetId)) return true;
    }
    return false;
  }

  function visibleUnableToBreedDialog() {
    const dialogs = [...(document.querySelectorAll?.('[role="dialog"], .ui-dialog') || [])];
    return dialogs.find(dialog => {
      const text = String(dialog?.textContent || "").replace(/\s+/g, " ").trim();
      const visible = dialog?.offsetParent !== null || dialog?.getClientRects?.().length > 0;
      return visible && /Unable to breed pets\.?/i.test(text);
    }) || null;
  }

  function dismissUnableToBreedDialog(dialog) {
    const buttons = [...(dialog?.querySelectorAll?.("button") || [])];
    const ok = buttons.find(button => /^OK$/i.test(String(button?.textContent || "").trim()));
    try { ok?.click?.(); } catch {}
  }

  function reply(requestId, ok, reason = "") {
    document.dispatchEvent(new CustomEvent(RESULT_EVENT, {
      detail: JSON.stringify({ requestId, ok, reason })
    }));
  }

  // Readiness probe only: reports whether the game's own dispatcher function exists yet.
  // It executes nothing and takes no parameters, so it is not a way to run arbitrary code
  // or commands — jobs use it to wait until OviPets has finished loading before they
  // read the page or send anything (sending too early corrupts data collection).
  document.addEventListener(PING_EVENT, event => {
    let requestId = "";
    try {
      requestId = String(JSON.parse(String(event.detail || "{}")).requestId || "");
    } catch {
      return;
    }
    const ready = typeof window.ui_action_cmdExec === "function";
    reply(requestId, ready, ready ? "" : "dispatcher-unavailable");
  });

  document.addEventListener(REQUEST_EVENT, event => {
    let request;
    try {
      request = JSON.parse(String(event.detail || "{}"));
    } catch {
      return;
    }
    const requestId = String(request.requestId || "");
    const command = String(request.command || "");
    const targetId = String(request.targetId ?? request.petId ?? "");
    const purpose = String(request.purpose || "");
    const ownHatchCommand = command === "pet_turn_egg"
      && purpose === "own-hatch"
      && isVisibleOwnHatchTarget(targetId);
    const fireAndForget = request.fireAndForget === true
      && (command === "pet_feed" || command === "friend_request" || ownHatchCommand);
    if (!requestId || !ALLOWED.has(command) || !/^\d+$/.test(targetId)
      || (command === "pet_turn_egg" && !ownHatchCommand)
      || (command === "pet_sendto" && !isConfirmedDiscard(command, purpose, request.fields))) {
      return reply(requestId, false, "invalid-command");
    }
    if (typeof window.ui_action_cmdExec !== "function") {
      return reply(requestId, false, "dispatcher-unavailable");
    }

    const form = document.createElement("form");
    // Mark temporary bridge DOM so the isolated-world MutationObserver can ignore the
    // append/remove churn generated by our own command transport.
    form.dataset.owehBridgeOwned = "1";
    form.method = "post";
    form.action = "/index.php";
    form.hidden = true;
    const fields = request.fields && typeof request.fields === "object" ? request.fields : {};
    for (const [name, value] of Object.entries(fields)) {
      if (!/^[A-Za-z][A-Za-z0-9_]*$/.test(name)) continue;
      const input = document.createElement("input");
      input.name = name;
      input.value = String(value ?? "");
      form.appendChild(input);
    }
    document.body.appendChild(form);

    let finished = false;
    let breedErrorObserver = null;
    const finish = (ok, reason = "") => {
      if (finished) return;
      finished = true;
      try { breedErrorObserver?.disconnect?.(); } catch {}
      form.remove();
      reply(requestId, ok, reason);
    };
    const timer = setTimeout(() => finish(false, "command-timeout"), 15000);
    const detectBreedRejection = () => {
      if (finished || command !== "pet_breed") return false;
      const dialog = visibleUnableToBreedDialog();
      if (!dialog) return false;
      clearTimeout(timer);
      dismissUnableToBreedDialog(dialog);
      finish(false, "unable-to-breed-pets");
      return true;
    };
    if (command === "pet_breed" && typeof MutationObserver === "function") {
      breedErrorObserver = new MutationObserver(() => detectBreedRejection());
      try { breedErrorObserver.observe(document.body, { childList: true, subtree: true, characterData: true }); } catch {}
    }
    try {
      let params;
      if (command === "friend_request" || command === "friend_remove") {
        params = `UserID=${targetId}`;
      } else if (command === "pet_breed") {
        const motherId = String(fields.MotherID || "");
        const fatherId = String(fields.FatherID || "");
        if (!/^\d+$/.test(motherId) || !/^\d+$/.test(fatherId)) {
          clearTimeout(timer);
          return finish(false, "invalid-breeding-pair");
        }
        params = `MotherID=${motherId}&FatherID=${fatherId}`;
      } else {
        params = `PetID=${targetId}`;
      }
      if (fireAndForget) {
        // Feed, friend-request and own-Hatchery hatch queues only need confirmation that
        // the game's own UI dispatcher accepted the command. Keep the form alive briefly because the
        // dispatcher may serialize it asynchronously, but do not wait for its server
        // callback before releasing the 100 ms queue lane.
        window.ui_action_cmdExec(command, params, form, () => {});
        clearTimeout(timer);
        finished = true;
        reply(requestId, true, "dispatched");
        const cleanupTimer = setTimeout(() => form.remove(), 5000);
        cleanupTimer?.unref?.();
        return;
      }
      window.ui_action_cmdExec(command, params, form, () => {
        clearTimeout(timer);
        finish(true);
      });
      // Some OviPets validation failures render a modal but never invoke the dispatcher
      // callback. Check once synchronously as well as through MutationObserver so those
      // failures are reported immediately instead of being mislabeled as a 15s timeout.
      detectBreedRejection();
    } catch (error) {
      clearTimeout(timer);
      finish(false, error?.message || "command-failed");
    }
  });
})();
